;;; -*- Mode: Emacs-Lisp -*-
;;; my color theme for in a 256 color terminal environment

;;-------------------------------------------------------------------------
;; Color Theme for use in the terminal! (256 color terminal!)
;;-------------------------------------------------------------------------
;;
;; based off zen-and-art color theme


(deftheme john-zen "The john zen theme")

(let ((class '((class color) (min-colors 89)))
      (ujelly-fg "#ffffff")
      (ujelly-bg "unspecified-bg")
      (ujelly-blue-0 "#8fbfdc")
      (ujelly-green-0 "#99ad6a")
      (ujelly-green-1 "#447799")
      (ujelly-green-2 "#a8ff60")
      (ujelly-grey-0 "#888888")
      (ujelly-grey-1 "#7f7f7f")
      (ujelly-grey-2 "#151515")
      (ujelly-orange-0 "#ffb964")
      (ujelly-purple-0 "#8197bf")
      (ujelly-purple-1 "#474e90")
      (ujelly-purple-2 "#cd00cd")
      (ujelly-red-0 "#cf6a4c")
      (ujelly-red-1 "#dd0093")
      (ujelly-red-2 "#de5577")
      (ujelly-yellow-0 "#fad07a")
      (ujelly-yellow-1 "#ffff00")
      (john-region      "#191717")
      (john-fg          "#d2dec4")
      (john-bg          "#100e0e")
      (john-white       "#ffffff")
      (john-black       "#000000")
      (john-brightblack "#7f7f7f")
      (john-gray-3      "#121212")
      (john-gray-2      "#3a3a3a")
      (john-gray-1      "#585858")
      (john-gray-00     "#808080")
      (john-gray-0      "#e4e4e4")
      (john-magit-gray  "grey30")
      (john-blue        "blue")
      (john-brightblue  "#00afff")
      (john-blue-0      "#0000ff")
      (john-brightgreen "#00ff00")
      (john-red-brown   "#875f5f")
      (john-brown       "#86453A")
      (john-orange      "#ff7800")
      (john-red         "red")
      (john-lightred    "tomato")
      (john-greengreen  "green")
      (john-green       "#5faf5f")
      (john-green-1     "#5a7644")
      (john-green-0     "MediumAquamarine")
      (john-blurple     "#46657B")
      (john-magenta     "#d787ff")
      (john-orchid      "#af87d7")
      (john-violet      "Blueviolet")
      (john-violet-0    "#8787ff")
      (john-cyan        "#ffff5f") ;; this is really some kind of yellow
      (john-yellow      "#C6B032")
      (john-yellow-1    "#00e5ee"))

  (custom-theme-set-faces
   'john-zen
   `(bold                                ((t (:bold t :foreground ,john-orange))))
   `(bold-italic                         ((t (:bold t :underline t))))
   `(border                              ((t (:foreground ,john-gray-0 :background ,john-gray-0))))
   `(buffer-menu-buffer                  ((t (:background ,john-brightblack :foreground ,john-gray-0))))
   `(button                              ((t (:foreground ,john-cyan :underline t))))
   ;; `(change-log-acknowledgement          ((t ())))
   ;; `(change-log-conditionals             ((t ())))
   ;; `(change-log-date                     ((t ())))
   ;; `(change-log-email                    ((t ())))
   ;; `(change-log-file                     ((t ())))
   ;; `(change-log-function                 ((t ())))
   ;; `(change-log-list                     ((t ())))
   ;; `(change-log-name                     ((t ())))
   ;; `(comint-highlight-input              ((t ())))
   ;; `(comint-highlight-prompt             ((t ())))
   ;; `(compilation-column-number           ((t ())))
   `(compilation-error                   ((,class (:foreground ,ujelly-red-0))))
   `(compilation-info                    ((,class (:foreground ,ujelly-yellow-0))))
   `(compilation-line-number             ((,class (:foreground ,ujelly-grey-0))))
   ;; `(compilation-warning                 ((t ())))
   ;; `(completions-annotations             ((t ())))
   ;; `(completions-common-part             ((t ())))
   ;; `(completions-first-difference        ((t ())))
   ;; `(css-property                        ((t ())))
   ;; `(css-selector                        ((t ())))
   ;; `(csv-separator-face                  ((t ())))
   ;; `(cua-global-mark                     ((t ())))
   ;; `(cua-rectangle                       ((t ())))
   ;; `(cua-rectangle-noselect              ((t ())))
   `(cursor                              ((,class (:foreground ,john-greengreen))))
   ;; `(custom-button                       ((t ())))
   ;; `(custom-button-mouse                 ((t ())))
   ;; `(custom-button-pressed               ((t ())))
   ;; `(custom-button-pressed-unraised      ((t ())))
   ;; `(custom-button-unraised              ((t ())))
   ;; `(custom-changed                      ((t ())))
   ;; `(custom-comment                      ((t ())))
   ;; `(custom-comment-tag                  ((t ())))
   ;; `(custom-documentation                ((t ())))
   ;; `(custom-face-tag                     ((t ())))
   ;; `(custom-group-tag                    ((t ())))
   ;; `(custom-group-tag-1                  ((t ())))
   ;; `(custom-invalid                      ((t ())))
   ;; `(custom-link                         ((t ())))
   ;; `(custom-modified                     ((t ())))
   ;; `(custom-rogue                        ((t ())))
   ;; `(custom-saved                        ((t ())))
   ;; `(custom-set                          ((t ())))
   ;; `(custom-state                        ((t ())))
   ;; `(custom-themed                       ((t ())))
   ;; `(custom-variable-button              ((t ())))
   ;; `(custom-variable-tag                 ((t ())))
   ;; `(custom-visibility                   ((t ())))
   `(default                             ((t (:foreground ,john-fg :background ,john-bg))))
   ;; `(diff-added                          ((t ())))
   ;; `(diff-changed                        ((t ())))
   ;; `(diff-context                        ((t ())))
   `(diff-file-header                    ((t (:background ,john-bg :foreground ,john-fg))))
   ;; `(diff-function                       ((t ())))
   `(diff-header                         ((t (:background ,john-bg :foreground ,john-fg))))
   ;; `(diff-hunk-header                    ((t ())))
   ;; `(diff-index                          ((t ())))
   ;; `(diff-indicator-added                ((t ())))
   ;; `(diff-indicator-changed              ((t ())))
   ;; `(diff-indicator-removed              ((t ())))
   ;; `(diff-nonexistent                    ((t ())))
   ;; `(diff-refine-change                  ((t ())))
   ;; `(diff-removed                        ((t ())))
   ;; `(dired-directory                     ((t ())))
   ;; `(dired-flagged                       ((t ())))
   ;; `(dired-header                        ((t ())))
   ;; `(dired-ignored                       ((t ())))
   ;; `(dired-mark                          ((t ())))
   ;; `(dired-marked                        ((t ())))
   ;; `(dired-perm-write                    ((t ())))
   ;; `(dired-symlink                       ((t ())))
   ;; `(dired-warning                       ((t ())))
   `(diredp-compressed-file-suffix       ((t (:foreground ,john-green-0))))
   `(diredp-date-time                    ((t (:foreground ,john-green-0))))
   `(diredp-deletion                     ((t (:foreground ,john-green-0))))
   `(diredp-deletion-file-name           ((t (:foreground ,john-green-0))))
   `(diredp-dir-heading                  ((t (:foreground ,john-green-0))))
   `(diredp-dir-priv                     ((t (:foreground ,john-green-0))))
   `(diredp-display-msg                  ((t (:foreground ,john-green-0))))
   `(diredp-exec-priv                    ((t (:foreground ,john-green-0))))
   `(diredp-executable-tag               ((t (:foreground ,john-green-0))))
   `(diredp-file-name                    ((t (:foreground ,john-blue))))
   `(diredp-file-suffix                  ((t (:foreground ,john-green-0))))
   `(diredp-flag-mark                    ((t (:background ,john-violet :foreground ,john-white))))
   `(diredp-flag-mark-line               ((t (:background ,john-bg :foreground ,john-violet))))
   `(diredp-ignored-file-name            ((t (:foreground ,john-green-0))))
   `(diredp-link-priv                    ((t (:foreground ,john-green-0))))
   `(diredp-no-priv                      ((t (:foreground ,john-green-0))))
   `(diredp-number                       ((t (:foreground ,john-green-0))))
   `(diredp-other-priv                   ((t (:foreground ,john-green-0))))
   `(diredp-rare-priv                    ((t (:foreground ,john-green-0))))
   `(diredp-read-priv                    ((t (:foreground ,john-green-0))))
   `(diredp-symlink                      ((t (:foreground ,john-green-0))))
   `(diredp-write-priv                   ((t (:foreground ,john-green-0))))
   ;; `(doctest-output-face                 ((t ())))
   ;; `(doctest-output-marker-face          ((t ())))
   ;; `(doctest-output-traceback-face       ((t ())))
   ;; `(doctest-prompt-face                 ((t ())))
   ;; `(doctest-results-divider-face        ((t ())))
   ;; `(doctest-results-header-face         ((t ())))
   ;; `(doctest-results-loc-face            ((t ())))
   ;; `(doctest-results-selection-face      ((t ())))
   ;; `(doctest-selection-face              ((t ())))
   ;; `(ediff-current-diff-A                ((t ())))
   ;; `(ediff-current-diff-Ancestor         ((t ())))
   ;; `(ediff-current-diff-B                ((t ())))
   ;; `(ediff-current-diff-C                ((t ())))
   `(ediff-even-diff-A                   ((t (:background "#444444"))))
   ;; `(ediff-even-diff-Ancestor            ((t ())))
   `(ediff-even-diff-B                   ((t (:background "#444444"))))
   ;; `(ediff-even-diff-C                   ((t ())))
   `(ediff-fine-diff-A ((t (:background "brightred" :foreground "black"))))
   ;; `(ediff-fine-diff-Ancestor            ((t ())))
   `(ediff-fine-diff-B ((t (:background "brightgreen" :foreground "black"))))
   ;; `(ediff-fine-diff-C                   ((t ())))
   `(ediff-odd-diff-A                    ((t (:background "#444444"))))
   ;; `(ediff-odd-diff-Ancestor             ((t ())))
   `(ediff-odd-diff-B                    ((t (:background "#444444"))))
   ;; `(ediff-odd-diff-C                    ((t ())))
   `(erc-notice-face                     ((,class (:foreground ,ujelly-yellow-0))))
   `(erc-prompt-face                     ((,class (:foreground ,ujelly-fg))))
   `(erc-timestamp-face                  ((,class (:foreground ,ujelly-purple-0))))
   ;; `(escape-glyph                        ((t ())))
   `(eshell-ls-directory                 ((,class (:weight normal :foreground ,ujelly-green-2))))
   `(eshell-ls-executable                ((,class (:foreground ,ujelly-red-0))))
   `(eshell-ls-symlink                   ((,class (:foreground ,ujelly-purple-2))))
   `(eshell-prompt                       ((,class (:foreground ,ujelly-red-0))))
   ;; `(file-name-shadow                    ((t ())))
   ;; `(fixed-pitch                         ((t ())))
   ;; `(flymake-errline                     ((t ())))
   ;; `(flymake-warnline                    ((t ())))
   ;; `(flyspell-duplicate                  ((t ())))
   ;; `(flyspell-incorrect                  ((t ())))
   `(font-latex-math-face                ((t (:foreground ,john-green))))
   `(font-lock-builtin-face              ((t (:foreground "#ff3f3f"))))
   `(font-lock-comment-delimiter-face    ((t (:foreground ,john-blurple))))
   `(font-lock-comment-face              ((t (:foreground ,john-red))))
   `(font-lock-constant-face             ((t (:foreground ,john-gray-00))))
   `(font-lock-doc-face                  ((t (:foreground ,john-blurple))))
   `(font-lock-doc-string-face           ((t (:foreground ,john-red))))
   `(font-lock-function-name-face        ((t (:foreground ,john-magenta))))
   `(font-lock-keyword-face              ((t (:foreground ,john-orange))))
   ;; `(font-lock-negation-char-face        ((t ())))
   `(font-lock-preprocessor-face         ((,class (:foreground ,john-red-brown))))
   `(font-lock-reference-face            ((t (:foreground ,john-yellow))))
   ;; `(font-lock-regexp-grouping-backslash ((t ())))
   ;; `(font-lock-regexp-grouping-construct ((t ())))
   `(font-lock-string-face               ((t (:foreground ,john-violet-0))))
   `(font-lock-type-face                 ((t (:foreground ,john-yellow-1))))
   `(font-lock-variable-name-face        ((t (:foreground ,john-greengreen))))
   `(font-lock-warning-face              ((,class (:foreground ,ujelly-red-1))))
   ;; `(fringe                              ((t ())))
   `(header-line                         ((,class (:foreground ,john-orange :background ,john-black))))
   ;; `(help-argument-name                  ((t ())))
   ;; `(highlight                           ((t ())))
   ;; `(highlight-changes                   ((t ())))
   ;; `(highlight-changes-delete            ((t ())))
   `(highlight-current-line-face         ((t (:background ,john-gray-3))))
   ;; `(hl-line                             ((t ())))
   `(ido-first-match                     ((,class (:foreground ,ujelly-yellow-0))))
   ;; `(ido-incomplete-regexp               ((t ())))
   ;; `(ido-indicator                       ((t ())))
   `(ido-only-match                      ((,class (:foreground ,ujelly-green-0))))
   `(ido-subdir                          ((,class (:foreground ,ujelly-fg))))
   ;; `(info-header-node                    ((t ())))
   ;; `(info-header-xref                    ((t ())))
   ;; `(info-menu-header                    ((t ())))
   ;; `(info-menu-star                      ((t ())))
   ;; `(info-node                           ((t ())))
   ;; `(info-title-1                        ((t ())))
   ;; `(info-title-2                        ((t ())))
   ;; `(info-title-3                        ((t ())))
   ;; `(info-title-4                        ((t ())))
   ;; `(info-xref                           ((t ())))
   ;; `(info-xref-visited                   ((t ())))
   `(isearch                             ((t (:underline t :background ,john-gray-0 :foreground ,john-black))))
   `(isearch-fail                        ((t (:underline t :background ,john-red :foreground ,john-black))))
   `(italic                              ((t (:underline t))))
   `(lazy-highlight                      ((t (:background ,john-gray-2))))
   `(lazy-highlight                      ((,class (:foreground "unspecified"))))
   `(link                                ((t (:foreground ,john-cyan))))
   ;; `(link-visited                        ((t ())))
   `(linum                               ((t (:background ,john-white :foreground ,john-black))))
   `(magit-branch                        ((,class (:foreground ,ujelly-red-2 :background ,john-bg :underline t))))
   `(magit-diff-added                    ((t (:foreground ,john-greengreen :background ,john-bg))))
   `(magit-diff-added-highlight          ((t (:foreground ,john-greengreen :background "grey10"))))
   `(magit-diff-removed                  ((t (:foreground ,john-red :background ,john-bg))))
   `(magit-diff-removed-highlight        ((t (:foreground ,john-red :background "grey10"))))
   `(magit-diff-file-heading             ((,class (:inherit nil))))
   `(magit-diff-file-heading-highlight   ((,class (:inherit magit-section-highlight))))
   `(magit-diff-hunk-heading             ((,class (:inherit nil :foreground ,ujelly-yellow-0))))
   `(magit-diff-hunk-heading-highlight   ((,class (:inherit nil :foreground ,ujelly-yellow-0 :background "grey10"))))
   `(magit-diff-context-highlight        ((,class (:inherit nil :background "grey10"))))
   `(magit-diffstat-added                ((,class (:foreground ,ujelly-green-0))))
   `(magit-header                        ((t (:foreground ,john-orange))))
   `(magit-item-highlight                ((t (:background ,john-region))))
   `(magit-log-graph                     ((t (:foreground ,john-magit-gray))))
   ;; `(magit-log-head-label-bisect-bad     ((t ())))
   ;; `(magit-log-head-label-bisect-good    ((t ())))
   ;; `(magit-log-head-label-local          ((t ())))
   ;; `(magit-log-head-label-remote         ((t ())))
   ;; `(magit-log-head-label-tags           ((t ())))
   ;; `(magit-log-message                   ((t ())))
   `(magit-log-sha1                      ((t (:foreground ,john-lightred))))
   ;; `(magit-log-tag-label                 ((t ())))
   `(magit-section-heading                 ((,class (:foreground ,john-orange :background ,john-black :underline t))))
   `(magit-section-highlight             ((,class (:background "grey10"))))
   `(magit-whitespace-warning-face       ((,class (:background ,ujelly-red-1))))
   ;; `(markdown-blockquote-face            ((t ())))
   ;; `(markdown-bold-face                  ((t ())))
   ;; `(markdown-comment-face               ((t ())))
   ;; `(markdown-header-face                ((t ())))
   ;; `(markdown-header-face-1              ((t ())))
   ;; `(markdown-header-face-2              ((t ())))
   ;; `(markdown-header-face-3              ((t ())))
   ;; `(markdown-header-face-4              ((t ())))
   ;; `(markdown-header-face-5              ((t ())))
   ;; `(markdown-header-face-6              ((t ())))
   ;; `(markdown-inline-code-face           ((t ())))
   ;; `(markdown-italic-face                ((t ())))
   ;; `(markdown-link-face                  ((t ())))
   ;; `(markdown-link-title-face            ((t ())))
   ;; `(markdown-list-face                  ((t ())))
   ;; `(markdown-math-face                  ((t ())))
   ;; `(markdown-pre-face                   ((t ())))
   ;; `(markdown-reference-face             ((t ())))
   ;; `(markdown-url-face                   ((t ())))
   ;; `(match                               ((t ())))
   ;; `(matlab-region-face                  ((t ())))
   ;; `(matlab-simulink-keyword-face        ((t ())))
   ;; `(matlab-unterminated-string-face     ((t ())))
   ;; `(menu                                ((t ())))
   ;; `(minibuffer-prompt                   ((t ())))
   `(mode-line                           ((t (:background ,john-white :foreground ,john-black))))
   ;; `(mode-line-buffer-id                 ((t ())))
   ;; `(mode-line-emphasis                  ((t ())))
   `(mode-line-highlight                 ((t (:background ,john-white :foreground ,john-gray-3))))
   `(mode-line-inactive                  ((t (:background ,john-gray-1 :foreground ,john-white))))
   ;; `(modeline-mousable                   ((t ())))
   ;; `(modeline-mousable-minor-mode        ((t ())))
   ;; `(mouse                               ((t ())))
   ;; `(mumamo-background-chunk-major       ((t ())))
   ;; `(mumamo-background-chunk-submode1    ((t ())))
   ;; `(mumamo-background-chunk-submode2    ((t ())))
   ;; `(mumamo-background-chunk-submode3    ((t ())))
   ;; `(mumamo-background-chunk-submode4    ((t ())))
   `(next-error                          ((t (:background ,john-gray-2 :foreground ,john-fg))))
   ;; `(nobreak-space                       ((t ())))
   `(org-checkbox                        ((,class (:foreground ,ujelly-orange-0))))
   `(org-level-1                         ((,class (:foreground ,ujelly-blue-0))))
   `(org-level-2                         ((,class (:foreground ,ujelly-yellow-0))))
   `(org-level-3                         ((,class (:foreground ,ujelly-purple-0))))
   ;; `(outline-1                           ((t ())))
   ;; `(outline-2                           ((t ())))
   ;; `(outline-3                           ((t ())))
   ;; `(outline-4                           ((t ())))
   ;; `(outline-5                           ((t ())))
   ;; `(outline-6                           ((t ())))
   ;; `(outline-7                           ((t ())))
   ;; `(outline-8                           ((t ())))
   `(paren-face-match-light              ((t (:background "#252323"))))
   ;; `(primary-selection                   ((t ())))
   ;; `(py-XXX-tag-face                     ((t ())))
   ;; `(py-builtins-face                    ((t ())))
   ;; `(py-class-name-face                  ((t ())))
   ;; `(py-decorators-face                  ((t ())))
   ;; `(py-exception-name-face              ((t ())))
   ;; `(py-pseudo-keyword-face              ((t ())))
   ;; `(query-replace                       ((t ())))
  `(region                              ((t (:background ,john-region))))
   ;; `(scroll-bar                          ((t ())))
   ;; `(secondary-selection                 ((t ())))
   ;; `(shadow                              ((t ())))
   ;; `(show-paren-match                    ((t ())))
   ;; `(show-paren-mismatch                 ((t ())))
   `(smerge-markers                      ((,class (:foreground ,ujelly-yellow-0))))
   `(smerge-refined-change               ((,class (:foreground ,ujelly-green-0))))
   ;; `(tool-bar                            ((t ())))
   ;; `(tooltip                             ((t ())))
   `(trailing-whitespace                 ((,class (:background ,ujelly-red-1))))
   `(underline                           ((t (:underline t))))
   ;; `(variable-pitch                      ((t ())))
   `(vertical-border                     ((t (:background ,john-gray-1 :foreground ,john-gray-0))))
   ;; `(widget-button                       ((t ())))
   ;; `(widget-button-pressed               ((t ())))
   ;; `(widget-documentation                ((t ())))
   ;; `(widget-field                        ((t ())))
   ;; `(widget-inactive                     ((t ())))
   ;; `(widget-single-line-field            ((t ())))
   ;; `(yas/field-debug-face                ((t ())))
   `(yas/field-highlight-face            ((t (:background ,john-red :foreground ,john-gray-3))))
   ;; `(zmacs-region                        ((t ())))
   ))

;;; ###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'john-zen)

;; (defun color-theme-john-super-theme ()
;;   "Irfn's zen with a bit of art and a bit of john."
;;   (interactive)
;;   (color-theme-install
;;    (append
;;     (list 'color-theme-john-super-theme
;;           `((background-color . ,john-black)
;;             (background-mode . dark)
;;             (border-color . ,john-black)
;;             (cursor-color . ,john-brightgreen)
;;             (foreground-color . ,john-fg)
;;             (list-matching-lines-face . bold)
;;             (view-highlight-face . highlight))
;;           )
;;     )
;;    )
;;   )
