;;; -*- Mode: Emacs-Lisp -*-
;;; my color theme for in a 256 color terminal environment

;;-------------------------------------------------------------------------
;; Color Theme for use in the terminal! (256 color terminal!)
;;-------------------------------------------------------------------------
;;
;; based off zen-and-art color theme

(defvar john-fg          "#d0d0d0")
(defvar john-bg          "#1c1c1c")
(defvar john-white       "#ffffff")
(defvar john-black       "#000000")
(defvar john-brightblack "#7f7f7f")
(defvar john-gray-2      "#3a3a3a")
(defvar john-gray-1      "#585858")
(defvar john-gray-0      "#e4e4e4")
(defvar john-blue        "blue")
(defvar john-brightblue  "#00afff")
(defvar john-blue-0      "#0000ff")
(defvar john-brightgreen "#00ff00")
(defvar john-red-brown   "#875f5f")
(defvar john-brown       "#86453A")
;; (defvar john-orange      "#AE5825")
(defvar john-orange      "#ff7800")
;;(defvar john-red         "#ff3030")
(defvar john-red         "red")
(defvar john-green       "#5faf5f")
(defvar john-green-1     "#5a7644")
(defvar john-green-0     "MediumAquamarine")
(defvar john-blurple     "#46657B")
(defvar john-magenta     "#d787ff")
(defvar john-orchid      "#af87d7")
(defvar john-violet      "Blueviolet")
(defvar john-violet-0    "#8787ff")
(defvar john-cyan        "#ffff5f")
(defvar john-yellow      "#C6B032")
(defvar john-yellow-1    "#00e5ee")

(defun color-theme-john-super-theme ()
  "Irfn's zen with a bit of art and a bit of john."
  (interactive)
  (color-theme-install
   (append
    (list 'color-theme-john-super-theme
          `((background-color . ,john-bg)
            (background-mode . dark)
            (border-color . ,john-black)
            (cursor-color . ,john-brightgreen)
            (foreground-color . ,john-fg)
            (list-matching-lines-face . bold)
            (view-highlight-face . highlight))

          `(bold                                ((t (:bold t))))
          `(bold-italic                         ((t (:bold t :underline t))))
          `(border                              ((t (:foreground ,john-gray-0 :background ,john-gray-0))))
          `(buffer-menu-buffer                  ((t (:background ,john-brightblack :foreground ,john-brightblack))))
          `(button                              ((t (:foreground ,john-blue-0 :underline t))))

          ;; (change-log-acknowledgement          ((t ())))
          ;; (change-log-conditionals             ((t ())))
          ;; (change-log-date                     ((t ())))
          ;; (change-log-email                    ((t ())))
          ;; (change-log-file                     ((t ())))
          ;; (change-log-function                 ((t ())))
          ;; (change-log-list                     ((t ())))
          ;; (change-log-name                     ((t ())))

          ;; (comint-highlight-input              ((t ())))
          ;; (comint-highlight-prompt             ((t ())))

          ;; (compilation-column-number           ((t ())))
          ;; (compilation-error                   ((t ())))
          ;; (compilation-info                    ((t ())))
          ;; (compilation-line-number             ((t ())))
          ;; (compilation-warning                 ((t ())))

          ;; (completions-annotations             ((t ())))
          ;; (completions-common-part             ((t ())))
          ;; (completions-first-difference        ((t ())))

          ;; (css-property                        ((t ())))
          ;; (css-selector                        ((t ())))

          ;; (csv-separator-face                  ((t ())))

          ;; (cua-global-mark                     ((t ())))
          ;; (cua-rectangle                       ((t ())))
          ;; (cua-rectangle-noselect              ((t ())))

          ;; (cursor                              ((t ())))

          ;; (custom-button                       ((t ())))
          ;; (custom-button-mouse                 ((t ())))
          ;; (custom-button-pressed               ((t ())))
          ;; (custom-button-pressed-unraised      ((t ())))
          ;; (custom-button-unraised              ((t ())))
          ;; (custom-changed                      ((t ())))
          ;; (custom-comment                      ((t ())))
          ;; (custom-comment-tag                  ((t ())))
          ;; (custom-documentation                ((t ())))
          ;; (custom-face-tag                     ((t ())))
          ;; (custom-group-tag                    ((t ())))
          ;; (custom-group-tag-1                  ((t ())))
          ;; (custom-invalid                      ((t ())))
          ;; (custom-link                         ((t ())))
          ;; (custom-modified                     ((t ())))
          ;; (custom-rogue                        ((t ())))
          ;; (custom-saved                        ((t ())))
          ;; (custom-set                          ((t ())))
          ;; (custom-state                        ((t ())))
          ;; (custom-themed                       ((t ())))
          ;; (custom-variable-button              ((t ())))
          ;; (custom-variable-tag                 ((t ())))
          ;; (custom-visibility                   ((t ())))

          `(default                             ((t (:foreground ,john-fg :background ,john-bg))))

          ;; (diff-added                          ((t ())))
          ;; (diff-changed                        ((t ())))
          ;; (diff-context                        ((t ())))
          ;; (diff-file-header                    ((t ())))
          ;; (diff-function                       ((t ())))
          ;; (diff-header                         ((t ())))
          ;; (diff-hunk-header                    ((t ())))
          ;; (diff-index                          ((t ())))
          ;; (diff-indicator-added                ((t ())))
          ;; (diff-indicator-changed              ((t ())))
          ;; (diff-indicator-removed              ((t ())))
          ;; (diff-nonexistent                    ((t ())))
          ;; (diff-refine-change                  ((t ())))
          ;; (diff-removed                        ((t ())))

          ;; (dired-directory                     ((t ())))
          ;; (dired-flagged                       ((t ())))
          ;; (dired-header                        ((t ())))
          ;; (dired-ignored                       ((t ())))
          ;; (dired-mark                          ((t ())))
          ;; (dired-marked                        ((t ())))
          ;; (dired-perm-write                    ((t ())))
          ;; (dired-symlink                       ((t ())))
          ;; (dired-warning                       ((t ())))

          ;; (diredp-compressed-file-suffix       ((t (:foreground ,john-green-0))))
          ;; (diredp-date-time                    ((t (:foreground ,john-green-0))))
          ;; (diredp-deletion                     ((t (:foreground ,john-green-0))))
          ;; (diredp-deletion-file-name           ((t (:foreground ,john-green-0))))
          ;; (diredp-dir-heading                  ((t (:foreground ,john-green-0))))
          ;; (diredp-dir-priv                     ((t (:foreground ,john-green-0))))
          ;; (diredp-display-msg                  ((t (:foreground ,john-green-0))))
          ;; (diredp-exec-priv                    ((t (:foreground ,john-green-0))))
          ;; (diredp-executable-tag               ((t (:foreground ,john-green-0))))
          `(diredp-file-name                    ((t (:foreground ,john-blue))))
          `(diredp-file-suffix                  ((t (:foreground ,john-green-0))))
          `(diredp-flag-mark                    ((t (:background ,john-violet :foreground ,john-white))))
          `(diredp-flag-mark-line               ((t (:background ,john-bg :foreground ,john-violet))))
          `(diredp-ignored-file-name            ((t (:foreground ,john-green-0))))
          `(diredp-link-priv                    ((t (:foreground ,john-green-0))))
          `(diredp-no-priv                      ((t (:foreground ,john-green-0))))
          `(diredp-number                       ((t (:foreground ,john-green-0))))
          `(diredp-other-priv                   ((t (:foreground ,john-green-0))))
          `(diredp-rare-priv                    ((t (:foreground ,john-green-0))))
          `(diredp-read-priv                    ((t (:foreground ,john-green-0))))
          `(diredp-symlink                      ((t (:foreground ,john-green-0))))
          `(diredp-write-priv                   ((t (:foreground ,john-green-0))))

          ;; (doctest-output-face                 ((t ())))
          ;; (doctest-output-marker-face          ((t ())))
          ;; (doctest-output-traceback-face       ((t ())))
          ;; (doctest-prompt-face                 ((t ())))
          ;; (doctest-results-divider-face        ((t ())))
          ;; (doctest-results-header-face         ((t ())))
          ;; (doctest-results-loc-face            ((t ())))
          ;; (doctest-results-selection-face      ((t ())))
          ;; (doctest-selection-face              ((t ())))

          ;; (ediff-current-diff-A                ((t ())))
          ;; (ediff-current-diff-Ancestor         ((t ())))
          ;; (ediff-current-diff-B                ((t ())))
          ;; (ediff-current-diff-C                ((t ())))
          ;; (ediff-even-diff-A                   ((t ())))
          ;; (ediff-even-diff-Ancestor            ((t ())))
          ;; (ediff-even-diff-B                   ((t ())))
          ;; (ediff-even-diff-C                   ((t ())))
          ;; (ediff-fine-diff-A                   ((t ())))
          ;; (ediff-fine-diff-Ancestor            ((t ())))
          ;; (ediff-fine-diff-B                   ((t ())))
          ;; (ediff-fine-diff-C                   ((t ())))
          ;; (ediff-odd-diff-A                    ((t ())))
          ;; (ediff-odd-diff-Ancestor             ((t ())))
          ;; (ediff-odd-diff-B                    ((t ())))
          ;; (ediff-odd-diff-C                    ((t ())))

          ;; (escape-glyph                        ((t ())))
          ;; (file-name-shadow                    ((t ())))
          ;; (fixed-pitch                         ((t ())))

          ;; (flymake-errline                     ((t ())))
          ;; (flymake-warnline                    ((t ())))

          ;; (flyspell-duplicate                  ((t ())))
          ;; (flyspell-incorrect                  ((t ())))

          `(font-latex-math-face                ((t (:foreground ,john-green))))
          `(font-lock-builtin-face              ((t (:foreground ,john-red-brown))))
          `(font-lock-comment-delimiter-face    ((t (:foreground ,john-blurple))))
          `(font-lock-comment-face              ((t (:foreground ,john-red))))
          `(font-lock-constant-face             ((t (:foreground ,john-cyan))))
          `(font-lock-doc-face                  ((t (:foreground ,john-blurple))))
          `(font-lock-doc-string-face           ((t (:foreground ,john-red))))
          `(font-lock-function-name-face        ((t (:foreground ,john-magenta))))
          `(font-lock-keyword-face              ((t (:foreground ,john-orange))))
          ;; (font-lock-negation-char-face        ((t ())))
          ;; (font-lock-preprocessor-face         ((t ())))
          `(font-lock-reference-face            ((t (:foreground ,john-yellow))))
          ;; (font-lock-regexp-grouping-backslash ((t ())))
          ;; (font-lock-regexp-grouping-construct ((t ())))
          `(font-lock-string-face               ((t (:foreground ,john-violet-0))))
          `(font-lock-type-face                 ((t (:foreground ,john-yellow-1))))
          `(font-lock-variable-name-face        ((t (:foreground ,john-green))))
          ;; (font-lock-warning-face              ((t ())))

          ;; (fringe                              ((t ())))

          ;; (header-line                         ((t ())))
          ;; (help-argument-name                  ((t ())))
          ;; (highlight                           ((t ())))
          ;; (highlight-changes                   ((t ())))
          ;; (highlight-changes-delete            ((t ())))
          ;; (highlight-current-line-face         ((t ())))
          ;; (hl-line                             ((t ())))

          ;; (ido-first-match                     ((t ())))
          ;; (ido-incomplete-regexp               ((t ())))
          ;; (ido-indicator                       ((t ())))
          ;; (ido-only-match                      ((t ())))
          ;; (ido-subdir                          ((t ())))

          ;; (info-header-node                    ((t ())))
          ;; (info-header-xref                    ((t ())))
          ;; (info-menu-header                    ((t ())))
          ;; (info-menu-star                      ((t ())))
          ;; (info-node                           ((t ())))
          ;; (info-title-1                        ((t ())))
          ;; (info-title-2                        ((t ())))
          ;; (info-title-3                        ((t ())))
          ;; (info-title-4                        ((t ())))
          ;; (info-xref                           ((t ())))
          ;; (info-xref-visited                   ((t ())))

          `(isearch                             ((t (:underline t :background ,john-gray-0 :foreground ,john-black))))
          `(isearch-fail                        ((t (:underline t :background ,john-red :foreground ,john-black))))

          ;; (italic                              ((t (:underline t))))

          ;; (lazy-highlight                      ((t ())))

          ;; (link                                ((t ())))
          ;; (link-visited                        ((t ())))

          `(linum                               ((t (:background ,john-white :foreground ,john-black))))

          ;; (magit-branch                        ((t ())))
          ;; (magit-diff-add                      ((t ())))
          ;; (magit-diff-del                      ((t ())))
          ;; (magit-diff-file-header              ((t ())))
          ;; (magit-diff-hunk-header              ((t ())))
          ;; (magit-diff-none                     ((t ())))
          ;; (magit-header                        ((t ())))
          ;; (magit-item-highlight                ((t ())))
          ;; (magit-item-mark                     ((t ())))
          ;; (magit-log-graph                     ((t ())))
          ;; (magit-log-head-label-bisect-bad     ((t ())))
          ;; (magit-log-head-label-bisect-good    ((t ())))
          ;; (magit-log-head-label-local          ((t ())))
          ;; (magit-log-head-label-remote         ((t ())))
          ;; (magit-log-head-label-tags           ((t ())))
          ;; (magit-log-message                   ((t ())))
          ;; (magit-log-sha1                      ((t ())))
          ;; (magit-log-tag-label                 ((t ())))
          ;; (magit-section-title                 ((t ())))

          ;; (markdown-blockquote-face            ((t ())))
          ;; (markdown-bold-face                  ((t ())))
          ;; (markdown-comment-face               ((t ())))
          ;; (markdown-header-face                ((t ())))
          ;; (markdown-header-face-1              ((t ())))
          ;; (markdown-header-face-2              ((t ())))
          ;; (markdown-header-face-3              ((t ())))
          ;; (markdown-header-face-4              ((t ())))
          ;; (markdown-header-face-5              ((t ())))
          ;; (markdown-header-face-6              ((t ())))
          ;; (markdown-inline-code-face           ((t ())))
          ;; (markdown-italic-face                ((t ())))
          ;; (markdown-link-face                  ((t ())))
          ;; (markdown-link-title-face            ((t ())))
          ;; (markdown-list-face                  ((t ())))
          ;; (markdown-math-face                  ((t ())))
          ;; (markdown-pre-face                   ((t ())))
          ;; (markdown-reference-face             ((t ())))
          ;; (markdown-url-face                   ((t ())))

          ;; (match                               ((t ())))

          ;; (matlab-region-face                  ((t ())))
          ;; (matlab-simulink-keyword-face        ((t ())))
          ;; (matlab-unterminated-string-face     ((t ())))

          ;; (menu                                ((t ())))

          ;; (minibuffer-prompt                   ((t ())))
          ;; (mode-line                           ((t ())))
          ;; (mode-line-buffer-id                 ((t ())))
          ;; (mode-line-emphasis                  ((t ())))
          ;; (mode-line-highlight                 ((t ())))
          ;; (mode-line-inactive                  ((t ())))
          ;; (modeline-mousable                   ((t ())))
          ;; (modeline-mousable-minor-mode        ((t ())))

          ;; (mouse                               ((t ())))

          ;; (mumamo-background-chunk-major       ((t ())))
          ;; (mumamo-background-chunk-submode1    ((t ())))
          ;; (mumamo-background-chunk-submode2    ((t ())))
          ;; (mumamo-background-chunk-submode3    ((t ())))
          ;; (mumamo-background-chunk-submode4    ((t ())))

          ;; (next-error                          ((t ())))
          ;; (nobreak-space                       ((t ())))
          ;; (outline-1                           ((t ())))
          ;; (outline-2                           ((t ())))
          ;; (outline-3                           ((t ())))
          ;; (outline-4                           ((t ())))
          ;; (outline-5                           ((t ())))
          ;; (outline-6                           ((t ())))
          ;; (outline-7                           ((t ())))
          ;; (outline-8                           ((t ())))

          ;; (paren-face-match-light              ((t ())))

          ;; (primary-selection                   ((t ())))

          ;; (py-XXX-tag-face                     ((t ())))
          ;; (py-builtins-face                    ((t ())))
          ;; (py-class-name-face                  ((t ())))
          ;; (py-decorators-face                  ((t ())))
          ;; (py-exception-name-face              ((t ())))
          ;; (py-pseudo-keyword-face              ((t ())))

          ;; (query-replace                       ((t ())))

          ;; (region                              ((t ())))

          ;; (scroll-bar                          ((t ())))
          
          ;; (secondary-selection                 ((t ())))
          ;; (shadow                              ((t ())))

          ;; (show-paren-match                    ((t ())))
          ;; (show-paren-mismatch                 ((t ())))

          ;; (tool-bar                            ((t ())))
          ;; (tooltip                             ((t ())))

          ;; (trailing-whitespace                 ((t ())))

          ;; (underline                           ((t (:underline t))))

          ;; (variable-pitch                      ((t ())))
          ;; (vertical-border                     ((t ())))

          ;; (viper-minibuffer-emacs              ((t ())))
          ;; (viper-minibuffer-insert             ((t ())))
          ;; (viper-minibuffer-vi                 ((t ())))
          ;; (viper-replace-overlay               ((t ())))
          ;; (viper-search                        ((t ())))

          ;; (widget-button                       ((t ())))
          ;; (widget-button-pressed               ((t ())))
          ;; (widget-documentation                ((t ())))
          ;; (widget-field                        ((t ())))
          ;; (widget-inactive                     ((t ())))
          ;; (widget-single-line-field            ((t ())))

          ;; (yas/field-debug-face                ((t ())))
          ;; (yas/field-highlight-face            ((t ())))

          ;; (zmacs-region                        ((t ())))

          )
    )
   )
  )
